import { User, Etablissement, Classe, Inscription, Cours, Devoir, Soumission, AppNotification } from "@/types";

export const initialEtablissements: Etablissement[] = [
  {
    id: "etab_lycee_excellence",
    name: "Lycée d'Excellence AlFasle",
    code: "ALF-EXC-01",
    subdomain: "lycee-excellence",
    type: "LYCEE",
    city: "Alger",
    country: "Algérie",
    address: "12 Avenue de l'Indépendance, Hydra",
    phone: "+213 21 00 11 22",
    email: "contact.lycee@alfasle.edu",
    description: "Établissement d'élite dispensant des formations scientifiques et technologiques d'excellence.",
    logoUrl: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=150&auto=format&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=80",
    directorName: "Dr. Mahamadou DIAWARA",
    directorEmail: "diawara@gmail.com",
    directorPassword: "Madouu1966@",
    status: "ACTIVE",
    subscriptionPlan: "ENTERPRISE",
    maxStudentsQuota: 500,
    maxClassesQuota: 20,
    classesCount: 4,
    studentsCount: 120,
    createdAt: "2025-01-01T08:00:00Z",
  },
  {
    id: "etab_college_el_manar",
    name: "Collège & Lycée El-Manar",
    code: "ALF-MAN-02",
    subdomain: "el-manar",
    type: "COLLEGE",
    city: "Oran",
    country: "Algérie",
    address: "45 Boulevard Front de Mer",
    phone: "+213 41 22 33 44",
    email: "direction@elmanar.edu",
    description: "Complexe éducatif moderne axé sur l'innovation pédagogique et le suivi personnalisé des élèves.",
    logoUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=150&auto=format&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&auto=format&fit=crop&q=80",
    directorName: "Mme Fatima Zahra",
    directorEmail: "fatima.zahra@elmanar.edu",
    status: "ACTIVE",
    subscriptionPlan: "PREMIUM",
    maxStudentsQuota: 300,
    maxClassesQuota: 15,
    classesCount: 3,
    studentsCount: 85,
    createdAt: "2025-01-15T08:00:00Z",
  },
  {
    id: "etab_polytech_kone",
    name: "Institut Supérieur Polytechnique KONE",
    code: "ALF-POL-03",
    subdomain: "polytech-kone",
    type: "INSTITUT",
    city: "Abidjan",
    country: "Côte d'Ivoire",
    address: "Plateau Dokui, Rue des Universités",
    phone: "+225 07 88 99 00",
    email: "admissions@polytech-kone.edu",
    description: "Institut supérieur d'ingénierie logicielle, data science, et design numérique.",
    logoUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=150&auto=format&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80",
    directorName: "Prof. Bakary Koné",
    directorEmail: "bakary.kone@polytech-kone.edu",
    status: "ACTIVE",
    subscriptionPlan: "ENTERPRISE",
    maxStudentsQuota: 1000,
    maxClassesQuota: 50,
    classesCount: 3,
    studentsCount: 95,
    createdAt: "2025-02-01T08:00:00Z",
  },
];

export const initialUsers: User[] = [
  {
    id: "u_super_admin_root",
    name: "KONE ADAMA (Super Admin Master)",
    username: "konedamaa",
    email: "konedamaa@gmail.com",
    password: "Madouu1966@",
    role: "SUPER_ADMIN",
    bio: "Super Administrateur Global de la Plateforme AlFasle Multi-Établissements.",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    createdAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "u_admin_diawara",
    name: "Dr. Mahamadou DIAWARA (Directeur)",
    username: "diawara",
    email: "diawara@gmail.com",
    password: "Madouu1966@",
    role: "ADMIN",
    bio: "Directeur & Administrateur Principal du Lycée d'Excellence AlFasle.",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    etablissementId: "etab_lycee_excellence",
    etablissementName: "Lycée d'Excellence AlFasle",
    createdAt: "2025-01-01T08:00:00Z",
  },
  {
    id: "u_admin_elmanar",
    name: "Mme Fatima Zahra",
    username: "fatima.zahra",
    email: "fatima.zahra@elmanar.edu",
    password: "Madouu1966@",
    role: "ADMIN",
    bio: "Directrice du Collège & Lycée El-Manar.",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    etablissementId: "etab_college_el_manar",
    etablissementName: "Collège & Lycée El-Manar",
    createdAt: "2025-01-15T08:00:00Z",
  },
  {
    id: "u_admin_polytech",
    name: "Prof. Bakary Koné",
    username: "bakary.kone",
    email: "bakary.kone@polytech-kone.edu",
    password: "Madouu1966@",
    role: "ADMIN",
    bio: "Directeur de l'Institut Supérieur Polytechnique KONE.",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    etablissementId: "etab_polytech_kone",
    etablissementName: "Institut Supérieur Polytechnique KONE",
    createdAt: "2025-02-01T08:00:00Z",
  },
  {
    id: "u_teacher_1",
    name: "Prof. Sarah Mansouri",
    username: "sarah",
    email: "sarah.mansouri@alfasle.edu",
    password: "Madouu1966@",
    role: "TEACHER",
    bio: "Enseignante en Informatique et Développement Web, 8 ans d'expérience dans l'enseignement supérieur.",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    etablissementId: "etab_lycee_excellence",
    etablissementName: "Lycée d'Excellence AlFasle",
    createdAt: "2025-01-10T10:00:00Z",
  },
  {
    id: "u_student_kone",
    name: "KONE (Élève Démo)",
    username: "kone",
    email: "kone@student.alfasle.edu",
    password: "Madouu1966@",
    role: "STUDENT",
    bio: "Élève assidu inscrit en Terminale S & Développement Logiciel.",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    etablissementId: "etab_polytech_kone",
    etablissementName: "Institut Supérieur Polytechnique KONE",
    createdAt: "2025-02-01T14:30:00Z",
  },
  {
    id: "u_student_1",
    name: "Amine Benali",
    username: "amine",
    email: "amine.benali@student.alfasle.edu",
    password: "Madouu1966@",
    role: "STUDENT",
    bio: "Étudiant passionné par le génie logiciel et les architectures cloud.",
    avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    etablissementId: "etab_lycee_excellence",
    etablissementName: "Lycée d'Excellence AlFasle",
    createdAt: "2025-02-01T14:30:00Z",
  },
  {
    id: "u_student_2",
    name: "Yasmine Khelifi",
    username: "yasmine",
    email: "yasmine.k@student.alfasle.edu",
    password: "Madouu1966@",
    role: "STUDENT",
    bio: "En reconversion professionnelle vers le développement frontend React/Next.js.",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    etablissementId: "etab_college_el_manar",
    etablissementName: "Collège & Lycée El-Manar",
    createdAt: "2025-02-05T09:15:00Z",
  },
  {
    id: "u_student_3",
    name: "Karim Ziani",
    username: "karim",
    email: "karim.ziani@student.alfasle.edu",
    password: "Madouu1966@",
    role: "STUDENT",
    bio: "Élève en sciences expérimentales et mathématiques.",
    avatarUrl: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80",
    etablissementId: "etab_lycee_excellence",
    etablissementName: "Lycée d'Excellence AlFasle",
    createdAt: "2025-02-12T16:45:00Z",
  },
  {
    id: "u_parent_1",
    name: "M. Ibrahima KONE (Parent)",
    username: "parent.kone",
    email: "parent.kone@gmail.com",
    password: "Madouu1966@",
    role: "PARENT",
    bio: "Parent d'élève - Tuteur légal.",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    childrenStudentIds: ["u_student_kone"],
    createdAt: "2025-02-15T08:00:00Z",
  },
];

export const initialClasses: Classe[] = [
  {
    id: "cls_nextjs_mastery",
    classCode: "AF-DEV-101",
    etablissementId: "etab_polytech_kone",
    etablissementName: "Institut Supérieur Polytechnique KONE",
    title: "Développement Web Moderne avec Next.js 15 & TypeScript",
    description: "Apprenez à concevoir des applications web complètes, rapides et sécurisées avec Next.js App Router, Tailwind CSS et Supabase.",
    level: "Intermédiaire",
    category: "Informatique",
    capacity: 35,
    enrollmentMode: "OPEN",
    status: "ACTIVE",
    teacherId: "u_teacher_1",
    teacherName: "Prof. Sarah Mansouri",
    coverImage: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&auto=format&fit=crop&q=80",
    startDate: "2026-09-15",
    endDate: "2026-12-20",
    createdAt: "2026-08-20T10:00:00Z",
    enrolledCount: 25,
    pendingCount: 2,
    coursesCount: 6,
    assignmentsCount: 3,
  },
  {
    id: "cls_algo_data",
    classCode: "AF-MATH-202",
    etablissementId: "etab_lycee_excellence",
    etablissementName: "Lycée d'Excellence AlFasle",
    title: "Terminale S : Mathématiques & Algorithmique Avancée",
    description: "Programme officiel de Terminale S : fonctions, suites, probabilités et algorithmique préparatoire aux concours.",
    level: "Avancé",
    category: "Mathématiques",
    capacity: 30,
    enrollmentMode: "OPEN",
    status: "ACTIVE",
    teacherId: "u_teacher_1",
    teacherName: "Prof. Sarah Mansouri",
    coverImage: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800&auto=format&fit=crop&q=80",
    startDate: "2026-09-20",
    endDate: "2026-12-15",
    createdAt: "2026-08-22T14:00:00Z",
    enrolledCount: 22,
    pendingCount: 0,
    coursesCount: 5,
    assignmentsCount: 3,
  },
  {
    id: "cls_physique_chimie",
    classCode: "AF-SCI-303",
    etablissementId: "etab_lycee_excellence",
    etablissementName: "Lycée d'Excellence AlFasle",
    title: "Physique & Chimie Fondamentale - 1ère & Terminale",
    description: "Mécanique newtonienne, électrostatique, ondes et réactions acido-basiques avec exercices corrigés et vidéos d'expériences.",
    level: "Intermédiaire",
    category: "Sciences",
    capacity: 28,
    enrollmentMode: "OPEN",
    status: "ACTIVE",
    teacherId: "u_teacher_1",
    teacherName: "Prof. Sarah Mansouri",
    coverImage: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&auto=format&fit=crop&q=80",
    startDate: "2026-09-18",
    endDate: "2026-12-18",
    createdAt: "2026-08-23T09:00:00Z",
    enrolledCount: 19,
    pendingCount: 1,
    coursesCount: 4,
    assignmentsCount: 2,
  },
  {
    id: "cls_ui_ux_design",
    classCode: "AF-DSG-404",
    etablissementId: "etab_college_el_manar",
    etablissementName: "Collège & Lycée El-Manar",
    title: "Design Numérique & Création Multimédia",
    description: "Créez des interfaces professionnelles, accessibles et esthétiques grâce à Figma et aux principes d'ergonomie moderne.",
    level: "Débutant",
    category: "Design",
    capacity: 30,
    enrollmentMode: "MANUAL_APPROVAL",
    status: "ACTIVE",
    teacherId: "u_teacher_1",
    teacherName: "Prof. Sarah Mansouri",
    coverImage: "https://images.unsplash.com/photo-1581291518655-9523c932edcf?w=800&auto=format&fit=crop&q=80",
    startDate: "2026-10-01",
    endDate: "2026-12-10",
    createdAt: "2026-08-25T11:00:00Z",
    enrolledCount: 15,
    pendingCount: 2,
    coursesCount: 3,
    assignmentsCount: 1,
  },
];

export const initialInscriptions: Inscription[] = [
  {
    id: "ins_kone_1",
    userId: "u_student_kone",
    userName: "KONE (Élève Démo)",
    userEmail: "kone@student.alfasle.edu",
    userPhone: "+225 07 12 34 56",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    role: "STUDENT",
    etablissementId: "etab_polytech_kone",
    etablissementName: "Institut Supérieur Polytechnique KONE",
    classeId: "cls_nextjs_mastery",
    classeTitle: "Développement Web Moderne avec Next.js 15 & TypeScript",
    status: "APPROVED",
    motivation: "Inscription principale en développement d'applications web.",
    appliedAt: "2026-08-27T10:00:00Z",
    reviewedAt: "2026-08-27T11:00:00Z",
    reviewedBy: "KONE ADAMA (Super Admin)",
  },
  {
    id: "ins_kone_2",
    userId: "u_student_kone",
    userName: "KONE (Élève Démo)",
    userEmail: "kone@student.alfasle.edu",
    userPhone: "+225 07 12 34 56",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    role: "STUDENT",
    etablissementId: "etab_lycee_excellence",
    etablissementName: "Lycée d'Excellence AlFasle",
    classeId: "cls_algo_data",
    classeTitle: "Terminale S : Mathématiques & Algorithmique Avancée",
    status: "APPROVED",
    motivation: "Préparation intensive au baccalauréat et concours d'ingénieurs.",
    appliedAt: "2026-08-28T09:00:00Z",
    reviewedAt: "2026-08-28T09:30:00Z",
    reviewedBy: "KONE ADAMA (Super Admin)",
  },
  {
    id: "ins_1",
    userId: "u_student_1",
    userName: "Amine Benali",
    userEmail: "amine.benali@student.alfasle.edu",
    userPhone: "+213 55 12 34 56",
    userAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    role: "STUDENT",
    etablissementId: "etab_lycee_excellence",
    etablissementName: "Lycée d'Excellence AlFasle",
    classeId: "cls_nextjs_mastery",
    classeTitle: "Développement Web Moderne avec Next.js 15 & TypeScript",
    status: "APPROVED",
    motivation: "Je souhaite perfectionner mes compétences en React et maîtriser l'écosystème Next.js pour mon projet de fin d'études.",
    appliedAt: "2026-08-28T14:20:00Z",
    reviewedAt: "2026-08-29T09:00:00Z",
    reviewedBy: "KONE ADAMA (Super Admin)",
  },
];

export const initialCourses: Cours[] = [
  {
    id: "crs_1",
    classeId: "cls_nextjs_mastery",
    chapterTitle: "Module 1 : Fondations & Architecture",
    title: "1. Introduction au App Router et aux Server Components (RSC)",
    summary: "Comprendre la séparation entre composants serveur et composants client, le rendu hybride et les performances.",
    order: 1,
    status: "PUBLISHED",
    publishedAt: "2026-09-01T08:00:00Z",
    video: {
      id: "vid_1",
      title: "Explication en direct : RSC vs Client Components",
      streamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      durationMinutes: 28,
      status: "READY",
    },
    content: `
### Objectifs de la session

1. Comprendre la différence fondamentale entre **React Server Components (RSC)** et **Client Components** (\`"use client"\`).
2. Réduire la taille du bundle JavaScript envoyé au navigateur client.
3. Exploiter le fetching de données direct en asynchrone côté serveur sans \`useEffect\`.

\`\`\`tsx
// Exemple de Server Component avec fetch direct
export default async function CourseList() {
  const res = await fetch("https://api.alfasle.edu/courses", { cache: "no-store" });
  const courses = await res.json();

  return (
    <ul className="space-y-3">
      {courses.map((course) => (
        <li key={course.id} className="p-4 bg-white rounded-lg shadow">
          {course.title}
        </li>
      ))}
    </ul>
  );
}
\`\`\`

> 💡 **Règle d'or :** Par défaut dans Next.js App Router, tous les composants sont des Server Components. N'ajoutez \`"use client"\` que si vous avez besoin de hooks interactifs (\`useState\`, \`useEffect\`, événements \`onClick\`).
    `,
    resources: [
      { name: "Guide_AppRouter_Architecture.pdf", url: "#", size: "2.4 Mo" },
      { name: "Snippets_Server_Components.zip", url: "#", size: "850 Ko" },
    ],
  },
  {
    id: "crs_2",
    classeId: "cls_nextjs_mastery",
    chapterTitle: "Module 1 : Fondations & Architecture",
    title: "2. Routage dynamique, Layouts imbriqués et Gestion des états",
    summary: "Structurer ses routes avec des paramètres dynamiques [slug], gérer les layouts partagés et les pages de chargement.",
    order: 2,
    status: "PUBLISHED",
    publishedAt: "2026-09-03T10:00:00Z",
    video: {
      id: "vid_2",
      title: "Tutoriel pas à pas : Création des layouts et loading.tsx",
      streamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
      durationMinutes: 34,
      status: "READY",
    },
    content: `
### Les fichiers spéciaux du dossier \`app/\`

- \`layout.tsx\` : Définit l'interface partagée entre plusieurs pages enfants (ne re-render pas lors de la navigation).
- \`page.tsx\` : Le composant principal associé à l'URL.
- \`loading.tsx\` : Affiché automatiquement via React Suspense pendant le chargement des données asynchrones.
- \`error.tsx\` : Capture les erreurs d'exécution pour éviter un crash global de la page.
    `,
  },
];

export const initialAssignments: Devoir[] = [
  {
    id: "dev_1",
    classeId: "cls_nextjs_mastery",
    coursId: "crs_1",
    coursTitle: "1. Introduction au App Router et aux Server Components (RSC)",
    title: "Devoir Pratique 1 : Création d'un catalogue de cours interactif",
    instructions: `
### Consignes du devoir :
1. Créez une application Next.js 15 avec TypeScript et Tailwind CSS.
2. Implémentez une page de liste utilisant un **Server Component** qui effectue un fetch de données.
3. Ajoutez un champ de recherche interactif côté client avec \`"use client"\` et synchronisez l'URL via \`useSearchParams\`.
4. Rédigez un court rapport explicatif (format PDF ou Markdown) et fournissez le lien de votre dépôt GitHub ainsi que la capture d'écran du résultat.
    `,
    dueDate: "2026-09-18T23:59:00Z",
    maxScore: 20,
    submissionsCount: 2,
    gradedCount: 1,
    createdAt: "2026-09-02T12:00:00Z",
    attachments: [
      { name: "Cahier_des_charges_Devoir_1.pdf", url: "#", size: "1.2 Mo" },
    ],
  },
  {
    id: "dev_2",
    classeId: "cls_nextjs_mastery",
    coursId: "crs_2",
    coursTitle: "2. Routage dynamique, Layouts imbriqués et Gestion des états",
    title: "Devoir Pratique 2 : Gestion des routes dynamiques & Formulaire de validation",
    instructions: "Créer les routes `/[classId]/lessons/[lessonId]` avec validation Zod et affichage des messages d'erreur.",
    dueDate: "2026-09-25T23:59:00Z",
    maxScore: 20,
    submissionsCount: 0,
    gradedCount: 0,
    createdAt: "2026-09-04T09:00:00Z",
  },
];

export const initialSubmissions: Soumission[] = [
  {
    id: "sub_1",
    devoirId: "dev_1",
    devoirTitle: "Devoir Pratique 1 : Création d'un catalogue de cours interactif",
    classeId: "cls_nextjs_mastery",
    classeTitle: "Développement Web Moderne avec Next.js 15 & TypeScript",
    studentId: "u_student_1",
    studentName: "Amine Benali",
    studentEmail: "amine.benali@student.alfasle.edu",
    studentAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    content: "Bonjour Madame, voici mon rendu pour le TP1. J'ai utilisé Server Components pour le rendu initial et un composant Client pour le filtre instantané avec debounce. Dépôt GitHub : https://github.com/amine-benali/alfasle-tp1",
    attachmentName: "Rapport_TP1_AmineBenali.pdf",
    attachmentUrl: "#",
    submittedAt: "2026-09-03T18:40:00Z",
    status: "GRADED",
    correction: {
      id: "cor_1",
      soumissionId: "sub_1",
      graderId: "u_teacher_1",
      graderName: "Prof. Sarah Mansouri",
      score: 18.5,
      maxScore: 20,
      feedback: "Excellent travail Amine ! La séparation entre composant serveur et client est parfaitement maîtrisée. L'utilisation du debounce pour la recherche est un vrai plus d'optimisation.",
      gradedAt: "2026-09-04T02:15:00Z",
    },
  },
  {
    id: "sub_2",
    devoirId: "dev_1",
    devoirTitle: "Devoir Pratique 1 : Création d'un catalogue de cours interactif",
    classeId: "cls_nextjs_mastery",
    classeTitle: "Développement Web Moderne avec Next.js 15 & TypeScript",
    studentId: "u_student_2",
    studentName: "Yasmine Khelifi",
    studentEmail: "yasmine.k@student.alfasle.edu",
    studentAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    content: "Bonjour, j'ai implémenté le catalogue avec Tailwind et Next.js 15. J'ai rencontré une petite difficulté sur la pagination que j'ai résolue avec router.push().",
    attachmentName: "Projet_Catalogue_Yasmine.zip",
    attachmentUrl: "#",
    submittedAt: "2026-09-04T01:10:00Z",
    status: "SUBMITTED",
  },
];

export const initialNotifications: AppNotification[] = [
  {
    id: "notif_1",
    userId: "u_teacher_1",
    title: "Nouvelle préinscription reçue",
    message: "Yasmine Khelifi a déposé une demande d'inscription pour la classe Next.js 15 & TypeScript.",
    type: "INSCRIPTION",
    isRead: false,
    createdAt: "2026-09-02T11:10:00Z",
  },
  {
    id: "notif_2",
    userId: "u_teacher_1",
    title: "Nouveau devoir remis",
    message: "Yasmine Khelifi a soumis le Devoir Pratique 1.",
    type: "ASSIGNMENT",
    isRead: false,
    createdAt: "2026-09-04T01:10:00Z",
  },
  {
    id: "notif_3",
    userId: "u_student_1",
    title: "Devoir corrigé !",
    message: "Votre note pour le Devoir Pratique 1 est disponible (18.5/20).",
    type: "GRADE",
    isRead: false,
    createdAt: "2026-09-04T02:15:00Z",
  },
];
