import { User, Etablissement, Classe, Inscription, Cours, Devoir, Soumission, AppNotification } from "@/types";

export const initialEtablissements: Etablissement[] = [
  {
    id: "etab_gs_alfasle",
    name: "Groupe Scolaire AlFasle",
    code: "GS-ALF-01",
    subdomain: "gs-alfasle",
    type: "LYCEE",
    city: "Abidjan",
    country: "Côte d'Ivoire",
    address: "Cocody Angré, Boulevard des Écoles",
    phone: "+225 07 00 11 22",
    email: "direction@gs-alfasle.edu",
    description: "Groupe scolaire d'excellence dispensant des formations scientifiques, générales et technologiques de haut niveau.",
    logoUrl: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=150&auto=format&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=80",
    directorName: "KONE ADAMA (Directeur)",
    directorEmail: "konedamaa@gmail.com",
    directorPassword: "Madouu1966",
    status: "ACTIVE",
    subscriptionPlan: "ENTERPRISE",
    maxStudentsQuota: 500,
    maxClassesQuota: 20,
    classesCount: 4,
    studentsCount: 120,
    createdAt: "2025-01-01T08:00:00Z",
  },
  {
    id: "etab_college_el_manar",
    name: "Collège & Lycée El-Manar",
    code: "ALF-MAN-02",
    subdomain: "el-manar",
    type: "COLLEGE",
    city: "Oran",
    country: "Algérie",
    address: "45 Boulevard Front de Mer",
    phone: "+213 41 22 33 44",
    email: "direction@elmanar.edu",
    description: "Complexe éducatif moderne axé sur l'innovation pédagogique et le suivi personnalisé des élèves.",
    logoUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=150&auto=format&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&auto=format&fit=crop&q=80",
    directorName: "Mme Fatima Zahra",
    directorEmail: "fatima.zahra@elmanar.edu",
    status: "ACTIVE",
    subscriptionPlan: "PREMIUM",
    maxStudentsQuota: 300,
    maxClassesQuota: 15,
    classesCount: 3,
    studentsCount: 85,
    createdAt: "2025-01-15T08:00:00Z",
  },
  {
    id: "etab_polytech_kone",
    name: "Institut Supérieur Polytechnique KONE",
    code: "ALF-POL-03",
    subdomain: "polytech-kone",
    type: "INSTITUT",
    city: "Abidjan",
    country: "Côte d'Ivoire",
    address: "Plateau Dokui, Rue des Universités",
    phone: "+225 07 88 99 00",
    email: "admissions@polytech-kone.edu",
    description: "Institut supérieur d'ingénierie logicielle, data science, et design numérique.",
    logoUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=150&auto=format&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80",
    directorName: "Prof. Bakary Koné",
    directorEmail: "bakary.kone@polytech-kone.edu",
    status: "ACTIVE",
    subscriptionPlan: "ENTERPRISE",
    maxStudentsQuota: 1000,
    maxClassesQuota: 50,
    classesCount: 3,
    studentsCount: 95,
    createdAt: "2025-02-01T08:00:00Z",
  },
];

export const initialUsers: User[] = [
  {
    id: "u_super_admin_root",
    name: "KONE ADAMA (Super Admin Master)",
    username: "konedamaa_root",
    email: "konedamaa@gmail.com",
    password: "Madouu1966",
    role: "SUPER_ADMIN",
    bio: "Super Administrateur Global de la Plateforme AlFasle Multi-Établissements.",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    createdAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "u_admin_kone",
    name: "KONE ADAMA (Directeur)",
    username: "konedamaa",
    email: "konedamaa@gmail.com",
    password: "Madouu1966",
    role: "ADMIN",
    bio: "Directeur & Administrateur Principal du Groupe Scolaire AlFasle.",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    etablissementId: "etab_gs_alfasle",
    etablissementName: "Groupe Scolaire AlFasle",
    createdAt: "2025-01-01T08:00:00Z",
  },
  {
    id: "u_admin_sanogo",
    name: "M. SANOGO (Directeur)",
    username: "sanogo",
    email: "sanogo@gmail.com",
    password: "Madouu1966",
    role: "ADMIN",
    bio: "Directeur d'Établissement au sein du réseau AlFasle.",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    etablissementId: "etab_gs_alfasle",
    etablissementName: "Groupe Scolaire AlFasle",
    createdAt: "2025-01-01T08:00:00Z",
  },
  {
    id: "u_admin_diawara",
    name: "Dr. Mahamadou DIAWARA",
    username: "diawara",
    email: "diawara@gmail.com",
    password: "Madouu1966",
    role: "ADMIN",
    bio: "Directeur Adjoint du Groupe Scolaire AlFasle.",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    etablissementId: "etab_gs_alfasle",
    etablissementName: "Groupe Scolaire AlFasle",
    createdAt: "2025-01-01T08:00:00Z",
  },
  {
    id: "u_admin_elmanar",
    name: "Mme Fatima Zahra",
    username: "fatima.zahra",
    email: "fatima.zahra@elmanar.edu",
    password: "Madouu1966@",
    role: "ADMIN",
    bio: "Directrice du Collège & Lycée El-Manar.",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    etablissementId: "etab_college_el_manar",
    etablissementName: "Collège & Lycée El-Manar",
    createdAt: "2025-01-15T08:00:00Z",
  },
  {
    id: "u_admin_polytech",
    name: "Prof. Bakary Koné",
    username: "bakary.kone",
    email: "bakary.kone@polytech-kone.edu",
    password: "Madouu1966@",
    role: "ADMIN",
    bio: "Directeur de l'Institut Supérieur Polytechnique KONE.",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    etablissementId: "etab_polytech_kone",
    etablissementName: "Institut Supérieur Polytechnique KONE",
    createdAt: "2025-02-01T08:00:00Z",
  },
  {
    id: "u_teacher_1",
    name: "Prof. Sarah Mansouri",
    username: "sarah",
    email: "sarah.mansouri@alfasle.edu",
    password: "Madouu1966@",
    role: "TEACHER",
    bio: "Enseignante en Informatique et Développement Web, 8 ans d'expérience dans l'enseignement supérieur.",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    etablissementId: "etab_gs_alfasle",
    etablissementName: "Groupe Scolaire AlFasle",
    createdAt: "2025-01-10T10:00:00Z",
  },
  {
    id: "u_student_kone",
    name: "KONE (Élève Démo)",
    username: "kone",
    email: "kone@student.alfasle.edu",
    password: "Madouu1966@",
    role: "STUDENT",
    bio: "Élève assidu inscrit en Terminale S & Développement Logiciel.",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    etablissementId: "etab_polytech_kone",
    etablissementName: "Institut Supérieur Polytechnique KONE",
    createdAt: "2025-02-01T14:30:00Z",
  },

  {
    id: "u_student_2",
    name: "Yasmine Khelifi",
    username: "yasmine",
    email: "yasmine.k@student.alfasle.edu",
    password: "Madouu1966@",
    role: "STUDENT",
    bio: "En reconversion professionnelle vers le développement frontend React/Next.js.",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    etablissementId: "etab_college_el_manar",
    etablissementName: "Collège & Lycée El-Manar",
    createdAt: "2025-02-05T09:15:00Z",
  },
  {
    id: "u_student_3",
    name: "Karim Ziani",
    username: "karim",
    email: "karim.ziani@student.alfasle.edu",
    password: "Madouu1966@",
    role: "STUDENT",
    bio: "Élève en sciences expérimentales et mathématiques.",
    avatarUrl: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80",
    etablissementId: "etab_gs_alfasle",
    etablissementName: "Groupe Scolaire AlFasle",
    createdAt: "2025-02-12T16:45:00Z",
  },
  {
    id: "u_parent_1",
    name: "M. Ibrahima KONE (Parent)",
    username: "parent.kone",
    email: "parent.kone@gmail.com",
    password: "Madouu1966@",
    role: "PARENT",
    bio: "Parent d'élève - Tuteur légal.",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    childrenStudentIds: ["u_student_kone"],
    createdAt: "2025-02-15T08:00:00Z",
  },
];

export const initialClasses: Classe[] = [
  {
    id: "cls_nextjs_mastery",
    classCode: "AF-DEV-101",
    etablissementId: "etab_polytech_kone",
    etablissementName: "Institut Supérieur Polytechnique KONE",
    title: "Développement Web Moderne avec Next.js 15 & TypeScript",
    description: "Apprenez à concevoir des applications web complètes, rapides et sécurisées avec Next.js App Router, Tailwind CSS et Supabase.",
    level: "Intermédiaire",
    category: "Informatique",
    capacity: 35,
    enrollmentMode: "OPEN",
    status: "ACTIVE",
    teacherId: "u_teacher_1",
    teacherName: "Prof. Sarah Mansouri",
    coverImage: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&auto=format&fit=crop&q=80",
    startDate: "2026-09-15",
    endDate: "2026-12-20",
    createdAt: "2026-08-20T10:00:00Z",
    enrolledCount: 25,
    pendingCount: 2,
    coursesCount: 6,
    assignmentsCount: 3,
  },
  {
    id: "cls_algo_data",
    classCode: "AF-MATH-202",
    etablissementId: "etab_gs_alfasle",
    etablissementName: "Groupe Scolaire AlFasle",
    title: "Terminale S : Mathématiques & Algorithmique Avancée",
    description: "Programme officiel de Terminale S : fonctions, suites, probabilités et algorithmique préparatoire aux concours.",
    level: "Avancé",
    category: "Mathématiques",
    capacity: 30,
    enrollmentMode: "OPEN",
    status: "ACTIVE",
    teacherId: "u_teacher_1",
    teacherName: "Prof. Sarah Mansouri",
    coverImage: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800&auto=format&fit=crop&q=80",
    startDate: "2026-09-20",
    endDate: "2026-12-15",
    createdAt: "2026-08-22T14:00:00Z",
    enrolledCount: 22,
    pendingCount: 0,
    coursesCount: 5,
    assignmentsCount: 3,
  },
  {
    id: "cls_physique_chimie",
    classCode: "AF-SCI-303",
    etablissementId: "etab_gs_alfasle",
    etablissementName: "Groupe Scolaire AlFasle",
    title: "Physique & Chimie Fondamentale - 1ère & Terminale",
    description: "Mécanique newtonienne, électrostatique, ondes et réactions acido-basiques avec exercices corrigés et vidéos d'expériences.",
    level: "Intermédiaire",
    category: "Sciences",
    capacity: 28,
    enrollmentMode: "OPEN",
    status: "ACTIVE",
    teacherId: "u_teacher_1",
    teacherName: "Prof. Sarah Mansouri",
    coverImage: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&auto=format&fit=crop&q=80",
    startDate: "2026-09-18",
    endDate: "2026-12-18",
    createdAt: "2026-08-23T09:00:00Z",
    enrolledCount: 19,
    pendingCount: 1,
    coursesCount: 4,
    assignmentsCount: 2,
  },
  {
    id: "cls_ui_ux_design",
    classCode: "AF-DSG-404",
    etablissementId: "etab_college_el_manar",
    etablissementName: "Collège & Lycée El-Manar",
    title: "Design Numérique & Création Multimédia",
    description: "Créez des interfaces professionnelles, accessibles et esthétiques grâce à Figma et aux principes d'ergonomie moderne.",
    level: "Débutant",
    category: "Design",
    capacity: 30,
    enrollmentMode: "MANUAL_APPROVAL",
    status: "ACTIVE",
    teacherId: "u_teacher_1",
    teacherName: "Prof. Sarah Mansouri",
    coverImage: "https://images.unsplash.com/photo-1581291518655-9523c932edcf?w=800&auto=format&fit=crop&q=80",
    startDate: "2026-10-01",
    endDate: "2026-12-10",
    createdAt: "2026-08-25T11:00:00Z",
    enrolledCount: 15,
    pendingCount: 2,
    coursesCount: 3,
    assignmentsCount: 1,
  },
];

export const initialInscriptions: Inscription[] = [];

export const initialCourses: Cours[] = [];

export const initialAssignments: Devoir[] = [];

export const initialSubmissions: Soumission[] = [];

export const initialNotifications: AppNotification[] = [];

